# Generated by Django 6.1 on 2026-08-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("author", models.CharField(max_length=256)),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD", "Hard"), ("SOFT", "Soft")],
                        default="HARD",
                        max_length=4,
                    ),
                ),
                ("inventory", models.PositiveIntegerField()),
                ("daily_fee", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                "ordering": ["title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "author"), name="unique_book"
                    )
                ],
            },
        ),
    ]
